### ISSUE TITLE
Incorrect address encoding for BCH

### ISSUE THREAD

**Issue by toxicologist** [sporestack/sporestack-python#3]
When launching a node with BCH selected as a currency, Sporestack incorrectly adds two iterations of the "bitcoincash:" prefix onto the address, making it unrecognizable by most wallets. This is especially inconvenient when trying to send from a mobile wallet using the QR code. Attatched screenshot displays the issue.
![bug](https://user-images.githubusercontent.com/30737140/37061133-3b3280ae-2171-11e8-9965-e5610136db50.png)

**Comment by teran-mckinney** [comment]
Thanks for your report! However, that should be fixed in 0.7.2: https://github.com/sporestack/sporestack-python/commit/a7294c375ed0f35fbf67a436d23f888daa3df748

Could you update and try again?

Unfortunately, didn't have any simple way to roll out cashaddr in a way that wouldn't fix that without upgrading.

**Comment by teran-mckinney** [comment]
Going to close this for now. Feel free to reopen it.
